### ISSUE TITLE
Hyperlink support

### ISSUE THREAD

**Issue by SolitudeSF** [c-blake/lc#1]
https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda
makes opening arbitrary files from terminal more convenient.

basically just have to wrap each displayed file into `"\e]8;;" & link & "\e\\" & text & "\e]8;;\e\\"` where `link` is `"file://" & absolute_path"`

**Comment by c-blake** [comment]
Thanks for working on this and apologies for not responding sooner.  I actually had it on some TODO list for a while, but never use a VTE terminal.  It's conceivable that in `procs` you could make pids hyperlinks for a fast `kill -KILL`.

I will be offline for the next couple of hours, but you seem to be on the right track.
